"""
Pydantic data models for VITALGUARD 2.0
Defines all request/response schemas used across the FastAPI application.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict
from datetime import datetime
from enum import Enum


class RiskLevel(str, Enum):
    """Risk classification levels based on risk score percentage."""
    GREEN = "green"    # 0-40%: Stable
    YELLOW = "yellow"  # 40-70%: Moderate
    RED = "red"        # 70-100%: Critical


class AlertType(str, Enum):
    """Types of alerts the intelligent alert engine can generate."""
    THRESHOLD = "threshold"    # Static vital threshold crossed
    SPIKE = "spike"            # Sudden risk score spike detected
    CONFIDENCE = "confidence"  # High-confidence critical prediction


class VitalsReading(BaseModel):
    """Single vitals reading snapshot for a patient."""
    timestamp: str
    hr: float = Field(..., description="Heart Rate (bpm)")
    spo2: float = Field(..., description="Oxygen Saturation (%)")
    sbp: float = Field(..., description="Systolic Blood Pressure (mmHg)")
    dbp: float = Field(..., description="Diastolic Blood Pressure (mmHg)")
    rr: float = Field(..., description="Respiration Rate (breaths/min)")
    temp: float = Field(..., description="Temperature (°C)")


class PatientBaseline(BaseModel):
    """Baseline (healthy) vital values for deviation detection."""
    hr: float = 72.0
    spo2: float = 98.0
    sbp: float = 120.0
    dbp: float = 80.0
    rr: float = 16.0
    temp: float = 36.8


class Patient(BaseModel):
    """Full patient record."""
    id: str
    name: str
    age: int
    bed: str
    admit_date: str
    baseline: PatientBaseline = PatientBaseline()
    risk_score: float = 0.0
    risk_level: RiskLevel = RiskLevel.GREEN
    confidence: float = 0.0
    status: str = "Active"


class PatientSummary(BaseModel):
    """Lightweight patient summary for the multi-patient dashboard."""
    id: str
    name: str
    bed: str
    risk_score: float
    risk_level: RiskLevel
    confidence: float
    status: str


class PredictionResult(BaseModel):
    """XGBoost prediction output for a patient."""
    patient_id: str
    timestamp: str
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Risk score 0-100%")
    risk_level: RiskLevel
    confidence: float = Field(..., ge=0.0, le=1.0)
    feature_contributions: Dict[str, float] = {}


class ForecastPoint(BaseModel):
    """Single point in the risk forecast timeline."""
    minutes_ahead: int
    predicted_risk: float
    lower_bound: float
    upper_bound: float


class RiskForecast(BaseModel):
    """15-30 min ahead risk forecast for a patient."""
    patient_id: str
    generated_at: str
    forecast: List[ForecastPoint]


class Alert(BaseModel):
    """Alert record generated by the intelligent alert engine."""
    id: str
    patient_id: str
    patient_name: str
    bed: str
    alert_type: AlertType
    message: str
    risk_score: float
    confidence: float
    timestamp: str
    suppressed: bool = False
    suppressed_at: Optional[str] = None
    suppressed_reason: Optional[str] = None


class AlertSuppressRequest(BaseModel):
    """Request body to suppress an alert."""
    reason: str = "Clinician reviewed"


class ICUSummary(BaseModel):
    """ICU-level aggregate metrics for the command center panel."""
    total_patients: int
    critical_count: int    # Red: 70-100%
    moderate_count: int    # Yellow: 40-70%
    stable_count: int      # Green: 0-40%
    alerts_triggered: int
    alerts_suppressed: int
    avg_risk_score: float
    system_stress_pct: float  # Average ICU risk index
